In [3]:
import numpy as np 

# Creating Numpy Arrays


In [9]:
li = [1,2,3,4,5]
arr = np.array(li)
print(arr)

[1 2 3 4 5]


In [10]:
type(arr)

numpy.ndarray

In [12]:
li = (1,2,3,4,5)
arr = np.array(li)
type(arr)

numpy.ndarray

# Defining The Range In Numpy Arrays

In [13]:
arr1 = np.arange(5,50,3)
print(arr1)

[ 5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Creating The arrays Through random in numpy

In [27]:
import seaborn as sns
# this tells that between 0 and 1 we want two numbers
arr2 = np.random.rand(10)
# create an array of random numbers and these numbers are between 0 and 1
arr2

array([0.94529669, 0.29145286, 0.7790286 , 0.67676887, 0.42880569,
       0.10938737, 0.36853824, 0.3897868 , 0.5903915 , 0.89395171])

In [22]:
arr3 = np.random.randn(5)
arr3
# this will throw a normal distribution in range -1 and 1 and the 5 passed implies it will give five elements

array([-0.77538284, -1.0399368 ,  0.94580448,  0.9972898 , -0.98837664])

In [37]:
arr4 = np.random.randint(10,50,5)
# this returns a numpy array in range 10 to 50 and it returns 5 eements
arr4
# this returns 5 random numbers between 10 and 50

array([10, 44, 23, 39, 42])

In [35]:
?np.random.randint

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 

# Getting the same elements 

In [46]:
arr5 = np.ones(5)
# return a new array of given shape and type filled with ones 
arr5

array([1., 1., 1., 1., 1.])

In [47]:
?np.ones

Signature: np.ones(shape, dtype=None, order='C')
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and order.

See Also
--------
ones_like : Return an array of ones with shape and type of input.
empty : Return a new uninitialized array.
zeros : Return a new array setting values to zero.
full : Return a new array of given shape filled with value.


Examples
--------
>>> np.ones(5)
array([1., 1., 1., 1., 1.])

>>> np.ones((5,), dtype=int)
array([1, 1, 1, 1, 1])

>>> np.ones((2, 1))
array([[1.],
    

In [48]:
# checking the data types of elements of the array 
arr5.dtype

dtype('float64')

# getting zero elements

In [54]:
arr6 = np.zeros(6)

# getting identity elements

In [52]:
arr7 = np.identity(5)

In [53]:
arr7

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Checking the dimensons of the array

In [57]:
# this gives us the array dimensiond
arr7.ndim

2

In [59]:
?np.ndarray.ndim

Type:        getset_descriptor
String form: <attribute 'ndim' of 'numpy.ndarray' objects>
Docstring:  
Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3


# np.linspace returns evenly spaced numbers over a sepcified interval 

In [60]:
?np.linspace

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : 

In [61]:
arr8 = np.linspace(5,20,5)

In [63]:
arr8 # this is an evenly spaced array of elements 

array([ 5.  ,  8.75, 12.5 , 16.25, 20.  ])

# Indexing in numpy array
 - positive indexing 
 - negative indexing

In [70]:
arr = np.arange(5,50,5)

In [73]:
arr[0] # finding the element at index 0 

5

In [74]:
arr[5] # indexing the fifth element 

30

# boolean opertions in and array

In [77]:
arr > 20 # this returns the boolen values for the arrays where the condition is true

array([False, False, False, False,  True,  True,  True,  True,  True])

# getting the elements of array where elements of array are greater than 20

In [78]:
arr[arr > 20]

array([25, 30, 35, 40, 45])

# Slicing in numpy

In [79]:
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [80]:
arr[2:5]

array([15, 20, 25])

In [82]:
# start indexing from the fourth element
arr[4:]

array([25, 30, 35, 40, 45])

In [83]:
arr[:5] # indexing upto the fifth element

array([ 5, 10, 15, 20, 25])

In [86]:
arr[-5:-1]
# the counting starts from -5 element and upto the -1 element 
# but the -1 element is ignored

array([25, 30, 35, 40])

In [87]:
arr[-5:]
# in this case the slicing starts from -5 element and goes to the end

array([25, 30, 35, 40, 45])

In [91]:
arr[-1:-5] # the array always goes from left to right so if we take indexing from -1 to -5 there are no
# elements on the left

array([], dtype=int32)

In [92]:
arr[-1:-5:-1] # in this case of we put -1 ir starts indexing from right to left

array([45, 40, 35, 30])

# adding the arrays

In [94]:
li = [1,2,3,4,5]
li1 = [4,5,6,7,8]
# if we add two lists the lists are concatenated
li + li1

[1, 2, 3, 4, 5, 4, 5, 6, 7, 8]

In [95]:
arr1 = np.arange(2,20,2)

# performing element wise addition

In [101]:
arr1 + arr

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63])

In [103]:
# getting the nnumber of elements present in the arrays 
arr12 = arr1 + arr

In [104]:
arr12.shape

(9,)

# subtracting the elements of the arrays 

In [106]:
li - li1

TypeError: unsupported operand type(s) for -: 'list' and 'list'

# subtracting the elements of an array

In [108]:
arr1 - arr # subtracting the elements of an array

array([ -3,  -6,  -9, -12, -15, -18, -21, -24, -27])

# multiply the elements of an array

In [109]:
arr * arr1

array([ 10,  40,  90, 160, 250, 360, 490, 640, 810])

# dividing the elements of array

In [112]:
arr / arr1

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [115]:
li * 3  # the elements of list are multiplied three times

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [116]:
li

[1, 2, 3, 4, 5]

# broadcasting the elements of an array

In [118]:
arr * 3

array([ 15,  30,  45,  60,  75,  90, 105, 120, 135])

In [119]:
arr + 3

array([ 8, 13, 18, 23, 28, 33, 38, 43, 48])

In [120]:
arr ** 2

array([  25,  100,  225,  400,  625,  900, 1225, 1600, 2025], dtype=int32)

In [124]:
arr % 2 # the modulo opration gives 1 for odd numbers and 0 for even numbers

array([1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [125]:
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])