In [3]:
import numpy as np 

# Creating Numpy Arrays


In [9]:
li = [1,2,3,4,5]
arr = np.array(li)
print(arr)

[1 2 3 4 5]


In [10]:
type(arr)

numpy.ndarray

In [12]:
li = (1,2,3,4,5)
arr = np.array(li)
type(arr)

numpy.ndarray

# Defining The Range In Numpy Arrays

In [13]:
arr1 = np.arange(5,50,3)
print(arr1)

[ 5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Creating The arrays Through random in numpy

In [16]:
# this tells that between 0 and 1 we want two numbers
arr2 = np.random.rand(2)
# create an array of random numbers and these numbers are between 0 and 1

In [17]:
arr2

array([0.62496645, 0.03178206])