In [3]:
import numpy as np 

# Creating Numpy Arrays


In [9]:
li = [1,2,3,4,5]
arr = np.array(li)
print(arr)

[1 2 3 4 5]


In [10]:
type(arr)

numpy.ndarray

In [12]:
li = (1,2,3,4,5)
arr = np.array(li)
type(arr)

numpy.ndarray

# Defining The Range In Numpy Arrays

In [13]:
arr1 = np.arange(5,50,3)
print(arr1)

[ 5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Creating The arrays Through random in numpy

In [27]:
import seaborn as sns
# this tells that between 0 and 1 we want two numbers
arr2 = np.random.rand(10)
# create an array of random numbers and these numbers are between 0 and 1
arr2

array([0.94529669, 0.29145286, 0.7790286 , 0.67676887, 0.42880569,
       0.10938737, 0.36853824, 0.3897868 , 0.5903915 , 0.89395171])

In [22]:
arr3 = np.random.randn(5)
arr3
# this will throw a normal distribution in range -1 and 1 and the 5 passed implies it will give five elements

array([-0.77538284, -1.0399368 ,  0.94580448,  0.9972898 , -0.98837664])

In [33]:
arr4 = np.random.randint(10,50,5)
# this returns a numpy array in range 10 to 50 and it returns 5 eements
arr4

array([48, 29, 46, 21, 18])

In [30]:
?np.random.randint

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 