In [1]:
import numpy as np 

# Creating Numpy Arrays


In [2]:
li = [1,2,3,4,5]
arr = np.array(li)
print(arr)

[1 2 3 4 5]


In [3]:
type(arr)

numpy.ndarray

In [4]:
li = (1,2,3,4,5)
arr = np.array(li)
type(arr)

numpy.ndarray

# Defining The Range In Numpy Arrays

In [5]:
arr1 = np.arange(5,50,3)
print(arr1)

[ 5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Creating The arrays Through random in numpy

In [6]:
import seaborn as sns
# this tells that between 0 and 1 we want two numbers
arr2 = np.random.rand(10)
# create an array of random numbers and these numbers are between 0 and 1
arr2

array([0.19637139, 0.5894286 , 0.95744343, 0.40472283, 0.87153471,
       0.58553154, 0.26498833, 0.6540047 , 0.78018137, 0.19484366])

In [7]:
arr3 = np.random.randn(5)
arr3
# this will throw a normal distribution in range -1 and 1 and the 5 passed implies it will give five elements

array([-1.04711443, -1.05945835,  3.26486822, -0.47337034,  0.10750632])

In [8]:
arr4 = np.random.randint(10,50,5)
# this returns a numpy array in range 10 to 50 and it returns 5 eements
arr4
# this returns 5 random numbers between 10 and 50

array([11, 21, 20, 10, 24])

# Getting the same elements 

In [9]:
arr5 = np.ones(5)
# return a new array of given shape and type filled with ones 
arr5

array([1., 1., 1., 1., 1.])

In [10]:
# checking the data types of elements of the array 
arr5.dtype

dtype('float64')

# getting zero elements

In [11]:
arr6 = np.zeros(6)

# getting identity elements

In [12]:
arr7 = np.identity(5)

In [13]:
arr7

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Checking the dimensons of the array

In [14]:
# this gives us the array dimensiond
arr7.ndim

2

# np.linspace returns evenly spaced numbers over a sepcified interval 

In [15]:
arr8 = np.linspace(5,20,5)

In [16]:
arr8 # this is an evenly spaced array of elements 

array([ 5.  ,  8.75, 12.5 , 16.25, 20.  ])

# Indexing in numpy array
 - positive indexing 
 - negative indexing

In [17]:
arr = np.arange(5,50,5)

In [18]:
arr[0] # finding the element at index 0 

5

In [19]:
arr[5] # indexing the fifth element 

30

# boolean opertions in and array

In [20]:
arr > 20 # this returns the boolen values for the arrays where the condition is true

array([False, False, False, False,  True,  True,  True,  True,  True])

# getting the elements of array where elements of array are greater than 20

In [21]:
arr[arr > 20]

array([25, 30, 35, 40, 45])

# Slicing in numpy

In [22]:
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
arr[2:5]

array([15, 20, 25])

In [24]:
# start indexing from the fourth element
arr[4:]

array([25, 30, 35, 40, 45])

In [25]:
arr[:5] # indexing upto the fifth element

array([ 5, 10, 15, 20, 25])

In [26]:
arr[-5:-1]
# the counting starts from -5 element and upto the -1 element 
# but the -1 element is ignored

array([25, 30, 35, 40])

In [27]:
arr[-5:]
# in this case the slicing starts from -5 element and goes to the end

array([25, 30, 35, 40, 45])

In [28]:
arr[-1:-5] # the array always goes from left to right so if we take indexing from -1 to -5 there are no
# elements on the left

array([], dtype=int32)

In [29]:
arr[-1:-5:-1] # in this case of we put -1 ir starts indexing from right to left

array([45, 40, 35, 30])

# adding the arrays

In [30]:
li = [1,2,3,4,5]
li1 = [4,5,6,7,8]
# if we add two lists the lists are concatenated
li + li1

[1, 2, 3, 4, 5, 4, 5, 6, 7, 8]

In [31]:
arr1 = np.arange(2,20,2)

# performing element wise addition

In [32]:
arr1 + arr

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63])

In [33]:
# getting the nnumber of elements present in the arrays 
arr12 = arr1 + arr

In [34]:
arr12.shape

(9,)

# subtracting the elements of the arrays 

In [35]:
li - li1

TypeError: unsupported operand type(s) for -: 'list' and 'list'

# subtracting the elements of an array

In [108]:
arr1 - arr # subtracting the elements of an array

array([ -3,  -6,  -9, -12, -15, -18, -21, -24, -27])

# multiply the elements of an array

In [109]:
arr * arr1

array([ 10,  40,  90, 160, 250, 360, 490, 640, 810])

# dividing the elements of array

In [112]:
arr / arr1

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [115]:
li * 3  # the elements of list are multiplied three times

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [116]:
li

[1, 2, 3, 4, 5]

# broadcasting the elements of an array

In [118]:
arr * 3

array([ 15,  30,  45,  60,  75,  90, 105, 120, 135])

In [119]:
arr + 3

array([ 8, 13, 18, 23, 28, 33, 38, 43, 48])

In [120]:
arr ** 2

array([  25,  100,  225,  400,  625,  900, 1225, 1600, 2025], dtype=int32)

In [124]:
arr % 2 # the modulo opration gives 1 for odd numbers and 0 for even numbers

array([1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [125]:
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

# sum of elements of an array

In [39]:
np.sum(arr)

225

In [40]:
arr.sum()

225

# mean of an array

In [42]:
np.mean(arr)

25.0

In [43]:
arr.mean()

25.0

In [60]:
np.mean([arr,arr1])

17.5

In [58]:
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [59]:
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [65]:
np.mean([arr1,arr])

17.5

# functions
    - min 
    - max 
    - std
    - np.median  


In [36]:
arr.min()

5

In [37]:
arr.max()

45

In [39]:
arr.std()

12.909944487358056

In [40]:
np.median(arr)

25.0

## median: divides data in two equal sets, left of median values are lower values, right of median value are higher values.

# finding -->> argmin : this returns the index value, of the minimum elements in the array

In [41]:
arr.argmin()

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [45]:
arr = np.array([0,25,75,12,45])

In [46]:
arr.argmin()

0

## argmax() ->> index value of maximum element in the array

In [48]:
arr.argmax()

2

# finding the index of elements

In [49]:
arr = np.arange(5,100)

In [51]:
arr[arr == 66]

array([66])

In [58]:
np.argwhere(arr == 66)

array([[61]], dtype=int64)

In [55]:
arr[61]

66

In [59]:
arr = np.arange(5,50,5)

In [60]:
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

# changing the dimensions of the array using reshape

In [65]:
arr = np.arange(5,50,5).reshape(3,3)
# left of the comma we have the rows and right of the comma we have the columns

In [66]:
arr 

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [74]:
arr = np.arange(5,50,6).reshape(4,2)

## Indexing the elements of 2d array

In [78]:
arr[0]

array([ 5, 11])

In [83]:
arr.reshape(2,4)

array([[ 5, 11, 17, 23],
       [29, 35, 41, 47]])

# transposing the elements of an array to reverse the dimensions

In [84]:
arr.T

array([[ 5, 17, 29, 41],
       [11, 23, 35, 47]])

In [85]:
arr.transpose()

array([[ 5, 17, 29, 41],
       [11, 23, 35, 47]])

array([[ 5, 11],
       [17, 23],
       [29, 35],
       [41, 47]])

In [88]:
arr.max()

47

In [90]:
arr.min()

5

In [91]:
arr.max(axis = 0) # finding the output vertically 

array([41, 47])

In [92]:
arr.max(axis = 1) # finding

array([11, 23, 35, 47])

# IN NUMPY 
    - axis = 0 is vertical along the columns 
    - axis = 1 is horizontal along the rows

# slicing the two dimensionsl aray

In [94]:
arr = np.arange(5,50,5).reshape(3,3)

In [107]:
arr[1:,1:]

array([[25, 30],
       [40, 45]])

In [111]:
arr[1:][1:]

array([[35, 40, 45]])

# float superseds integers

In [117]:
arr = np.array([1,2,3.0,4])
arr

array([1., 2., 3., 4.])

# character superseds flota and integers

In [115]:
arr = np.array([1,2,'hello',5.0])

In [116]:
arr

array(['1', '2', 'hello', '5.0'], dtype='<U11')

In [118]:
arr = np.array(['1','2',3,4])

In [119]:
arr

array(['1', '2', '3', '4'], dtype='<U1')

In [124]:
arr.astype(np.int64)

array([1, 2, 3, 4], dtype=int64)

In [125]:
arr.astype(np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [129]:
arr = np.arange(5,50,5).reshape(3,3)

In [134]:
arr[:2,1:]

array([[10, 15],
       [25, 30]])

In [145]:
arr[1:,:2].T

array([[20, 35],
       [25, 40]])

In [152]:
arr = np.arange(5,50).reshape(3,3,5)

In [154]:
arr[0]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [161]:
arr[1][1:,3:]

array([[28, 29],
       [33, 34]])

In [156]:
arr[2]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [157]:
arr.ndim

3

In [6]:

import numpy as np

# solving equations in numpy 

### 2x + 3y = 7 
### 5x + 4y = 9

In [8]:
a = np.array([[2,3],[5,4]])
b = np.array([7,9])

In [10]:
x = np.linalg.solve(a,b)

In [11]:
np.allclose(np.dot(a, x), b)

True

In [12]:
x

array([-0.14285714,  2.42857143])

# Solving Three Equations in numpy

### 2x + 3y - 7z = 49 
### 3x - 12y + 6z = 34 
### 5x + 10y -11z = 21

In [20]:
a = np.array([[2,3,-7],[3,-12,6],[5,10,-11]])
b = np.array([49,34,21])

In [41]:
np.linalg.solve(a,b)

array([ -2.97643098,  -9.54882155, -11.94276094])

# mangos and oranges problems

In [43]:
a = np.array([[20,10],[17,22]])
b = np.array([350,500])

In [44]:
np.linalg.solve(a,b)

array([10., 15.])

# understanding numpy where 

In [47]:
arr = np.arange(5,30)

In [48]:
np.where(arr > 15, arr, arr * 10)

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29])

In [49]:
arr < 15

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [50]:
len(arr)

25

# not a number in numpy

In [51]:
arr = np.array([1,2,3,np.nan])

In [53]:
len(arr)

4